version: 2.1

jobs:
  test_backend:
    docker:
      - image: circleci/openjdk:9-jdk-sid-node-browsers
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_database
      - image: circleci/mongo:latest
        environment:
          MONGODB_DATABASE: content_database
    steps:
      - checkout
      - run: cd backend && ./gradlew build

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test_backend

