version: "3.3"
services:

  # frontend:
  # backend:
  ml_backend:
    image: socialclusters/ml_backend
    depends_on:
      - backend
      - content_database
      - user_database
    ports:
      - "5000:5000"

  backend:
    image: socialclusters/backend
    depends_on:
      - content_database
      - user_database
    ports:
      - "8080:8080"

  content_database:
    container_name: content_database
    image: mongo:latest
    volumes:
    - ./mongodb/data/db:/data/db
    ports:
    - "27017:27017"
    environment:
    - MONGODB_DATABASE=content_database # TODO - Name

  user_database:
    container_name: user_database
    image: postgres:10.5
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
    - POSTGRES_DB=user_database # TODO - Name
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
