version: "3.3"
services:
  nginx:
    image: socialclusters/nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"

  #  ofelia:
  #    image: mcuadros/ofelia:latest

  frontend:
    image: socialclusters/frontend
    depends_on:
      - content_database
      - user_database
      - backend
      - topic_analysis_service
      - platform_api_service
    ports:
      - "3000:3000"

  topic_analysis_service:
    image: socialclusters/topic_analysis_service
    depends_on:
      - content_database
      - user_database
    ports:
      - "5000:5000"

  platform_api_service:
    image: socialclusters/platform_api_service
    depends_on:
      - content_database
      - user_database
    ports:
      - "6000:6000"

  backend:
    image: socialclusters/backend
    depends_on:
      - content_database
      - user_database
      - topic_analysis_service
      - platform_api_service
    ports:
      - "8080:8080"
