spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: content_database

  datasource:
    jdbc-url: jdbc:postgresql://localhost:3312/user_database
    username: postgres
